name: mathgame
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  get_it: ^7.6.7
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  just_audio: ^0.9.36
  easy_localization: ^3.0.5
  url_launcher: ^6.2.5
  video_player: ^2.8.3
  launch_review: ^3.0.1
  flutter_shakemywidget: ^1.0.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/launcher_icon.png"

flutter:

  uses-material-design: true


  assets:
    - assets/database/math_game.db
    - assets/images/
    - assets/audio/
    - assets/translation/



  fonts:
    - family: SmartKid
      fonts:
        - asset: assets/fonts/smart_kid.ttf
    - family: WickedMouse
      fonts:
        - asset: assets/fonts/wicked_mouse.ttf
    - family: BubbleGumSans
      fonts:
        - asset: assets/fonts/bubblegumsans_regular.ttf
